name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main, develope]
    types: [completed]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: $default-branch

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - uses: pandoc/actions/setup@v1.1.0
      - name: Setup Repo
        if: ${{ github.ref == 'refs/heads/main' }}
        # main branch
        uses: actions/checkout@v4
      - name: Setup Repo for PR
        if: github.event_name == 'pull_request'
        # pull request
        id: checkout_pr
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha }}
      - name: Setup Repo for Dispatch
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.branch
        # workflow_dispatch with branch input
        id: checkout_dispatch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x.x

      - name: Install dependencies
        run: deno install
      - name: Run build
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: deno run build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'github-pages' || 'github-pages-preview' }}
      url: ${{ github.ref == 'refs/heads/main' && steps.deployment.outputs.page_url || format(steps.deployment.outputs.page_url, '/preview', github.event.pull_request.number) }}
    
    outputs:
      deployment_url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: ${{ github.ref == 'refs/heads/main' && 'Deploy to GitHub Pages' || 'Deploy Preview to GitHub Pages' }}
        uses: actions/deploy-pages@v4
        with:
          preview: ${{ github.event_name == 'pull_request_target' || github.event_name == 'workflow_dispatch' }}

      - name: Comment Deployment URL
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            Deployed to [${{ steps.deployment.outputs.page_url }}](${{ steps.deployment.outputs.page_url }}) 🎉
            This is a preview deployment for PR #${{ github.event.pull_request.number }}.
            You can view the changes made in this PR by clicking the link above.
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: 'jonathonrp-portfolio-preview'
